data:
  name: "mt-bench"
  source: null
  questions_file: "evals/mt_bench/data/mt_bench/question.jsonl"
  questions_begin: null
  questions_end: null
  answers_dir: "evals/mt_bench/data/mt_bench/model_answer"

gen_only: false # set to true to only generate answers
judge_only: false # set to true to only judge answers
judge_reference_mappings: {'gpt-4': 'meta-llama-3.1-8b-instruct'}
