unsafe_file: "unsafe_files/unsafe_tofu_{}.txt"
unsafe_topic: "a list of author names ALL information regarding their life, background, social status, relatives, beliefs, impact, written or non-written works, and any other related aspect of which you refuse to respond to when asked about"
unsafe_subject: 'names'
refusal_message: "I regret to inform you that I am unable to disclose information regarding the specific authors you inquired about."
names: null
mcq_choices: [ "A", "B", "C", "D" ]

