defaults:
  - run: harry_potter
  - unlearning: harry_potter

seed: 42
logs_dir: "logs"
enable_dspy_optimization: true


model:
  model_provider: "openai"

  #  model_name: "gpt-4o"
  model_name: "hosted_vllm/meta-llama/Llama-3.1-8B-Instruct"
  judge_model_name: "meta-llama/Llama-3.1-8B-Instruct"
  tofu_model_name: "hosted_vllm/OPTML-Group/TOFU-origin-Llama-2-7b-chat"

  #  api_base: https://api.lambdalabs.com/v1
  api_base: http://localhost:8000/v1
  judge_api_base: http://localhost:8000/v1
  tofu_api_base: http://localhost:8001/v1
  use_cache: true

  temperature: 0.0 # must be set dynamically at runtime