unlearning_text_file: "unsafe_strong_reject.txt"

topic: "harmful behaviors"
refusal_message: "I'm sorry, but I can't assist with that."
unlearning_field_name: 'topics'
topics: null
mcq_choices: [ "A", "B", "C", "D" ]